# Generated by Django 5.1.6 on 2025-03-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_images/'),
        ),
    ]
