# Generated by Django 5.1.6 on 2025-03-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_featured',
        ),
    ]
